version: "3.7"
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rDcof4i1tmIrUhk2CtUPpNEIAST1T6WW
      MONGO_INITDB_DATABASE: safewalk
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
